### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by sonewman** [domadams/essential-ui#1]
If the module is installed globally

```
$ npm install -g essential-ui
```

you won't be able to import it:

``` javascript
import {Button} from 'essential-ui';
```

Unless you do:

```
npm link essential-ui
```

in your project directory.

Also we should publish even an empty `readme.md` to npm to secure the package name :smile:

**Comment by sonewman** [comment]
It might actually be worth adding a package json in the `dist` folder, that way you could publish the compiled source similar to what Facebook dow with React :smiley:

**Comment by punmechanic** [comment]
You shouldn't be installing this module globally - this behaviour occurs with nearly every other npm module.

Install it locally using `--save`, `--save-exact` or `--save-dev`

**Comment by domadams** [comment]
Yes have updated the readme so that people do not install this globally. Thanks for pointing this out :+1:
